In [2]:
import torch
import numpy as np

## Torch Autograd

*  Pytorch automatically computes gradient of operations (or fucntions)

### Case 1. $R^n \rightarrow R$



* $\vec{x} = [x_1,x_2,x_3,....,x_n] $ 
 
* $f(x) = ||\vec{x}|| = \sqrt{x_1^2 + x_2^2 + x_3^2 + ...+x_n^2} $


* $\frac{\partial \vec{f}}{\partial x_j} = 2 x_j $

In [3]:
x = torch.tensor(np.arange(10).astype(float),requires_grad=True)
y = torch.norm(x)
y.backward()
x.grad

tensor([0.0000, 0.0592, 0.1185, 0.1777, 0.2369, 0.2962, 0.3554, 0.4146, 0.4739,
        0.5331], dtype=torch.float64)

In [4]:
# check the differentiation using the exact formula 
def dy_dx(x):
    norm = np.sqrt(np.sum(x**2))
    return x/norm

x_np = np.arange(10)
x_grad = dy_dx(x_np)
print(x_grad)

[0.         0.05923489 0.11846978 0.17770466 0.23693955 0.29617444
 0.35540933 0.41464421 0.4738791  0.53311399]


In [5]:
y

tensor(16.8819, dtype=torch.float64, grad_fn=<LinalgVectorNormBackward0>)

### Case 2: $R^n \rightarrow R^n$

* $\vec{x} = [x_1,x_2,x_3,....,x_n]$ 

* $\vec{f(x)} = [x_1^2 , x_2^2 , x_3^2 , ...,x_n^2] $

* $ \frac{\partial \vec{f}}{\partial \vec{x}} = [\frac{\partial \vec{f}}{\partial x_1},\frac{\partial \vec{f}}{\partial x_2},\frac{\partial \vec{f}}{\partial x_3},.....,
\frac{\partial \vec{f}}{\partial x_n}] $

In [6]:
x.detach()
x = torch.tensor(np.arange(10).astype(float),requires_grad=True)
y2 = x**2
y2.backward(torch.ones(10))
x.grad

tensor([ 0.,  2.,  4.,  6.,  8., 10., 12., 14., 16., 18.], dtype=torch.float64)

In [7]:
# check the solution using the exact formula 
def dy2_dx(x):
    return 2*x

x_grad = dy2_dx(x_np)
print(x_grad)

[ 0  2  4  6  8 10 12 14 16 18]


### Example 


$$ \vec{Q} = 3 \vec{a}^3 - \vec{b}^2  $$ 

$$ \vec{a} = \begin{pmatrix} a_1 \\ a_2 \end{pmatrix} $$ 

$$ \vec{b} = \begin{pmatrix} b_1 \\ b_2 \end{pmatrix} $$


$$\vec{Q} = \begin{pmatrix} Q_1 \\ Q_2 \end{pmatrix} = \begin{pmatrix} 3 a_1^3 - b_1^2 \\ 3 a_2^3 - b_2^2 \end{pmatrix} $$

$$\vec{J} = \begin{pmatrix} \frac{\partial Q_1}{\partial a_1} & \frac{\partial Q_1}{\partial b_1} & \frac{\partial Q_1}{\partial a_2} & \frac{\partial Q_1}{\partial b_2} \\ 
\frac{\partial Q_2}{\partial a_1} & \frac{\partial Q_2}{\partial b_1} & \frac{\partial Q_2}{\partial a_2} & \frac{\partial Q_2}{\partial b_2}  \end{pmatrix}  $$

$$\vec{J} = \begin{pmatrix} 9 a_1^2 & -2 b_1 & 0 & 0\\ 
0 & 0 & 9 a_2^2 & -2 b_2  \end{pmatrix}  $$


$$\vec{J}^T \cdot v^T = \begin{pmatrix} 9 a_1^2 & 0\\ 
                                        -2 b_1 & -0 \\
                                        0 & 9 a_2^2 \\
                                        0 & -2 b_2 \\
                                         \end{pmatrix}  \cdot \begin{pmatrix} 
                                         1\\ 
                                         1
                                         \end{pmatrix} = \begin{pmatrix} 9 a_1^2 \\ 
                                        -2 b_1  \\
                                        9 a_2^2 \\
                                       -2 b_2 \end{pmatrix}$$

In [8]:
a = torch.tensor(np.arange(4).astype(float),requires_grad=True)
b = torch.tensor(np.arange(0,13,4).astype(float),requires_grad=True)

In [9]:
a

tensor([0., 1., 2., 3.], dtype=torch.float64, requires_grad=True)

In [10]:
b

tensor([ 0.,  4.,  8., 12.], dtype=torch.float64, requires_grad=True)

In [11]:
Q = 3*a**3 - b**2

In [12]:
Q

tensor([  0., -13., -40., -63.], dtype=torch.float64, grad_fn=<SubBackward0>)

In [13]:
Q.backward(torch.ones(4))
a.grad

tensor([ 0.,  9., 36., 81.], dtype=torch.float64)

In [14]:
b.grad

tensor([ -0.,  -8., -16., -24.], dtype=torch.float64)

In [15]:
# test the gradients using the exact values 

def dQ_da(x):
    return 9*x**2

def dQ_db(x):
    return -2*x

dQ_da(a)

tensor([ 0.,  9., 36., 81.], dtype=torch.float64, grad_fn=<MulBackward0>)

In [16]:
dQ_db(b)

tensor([ -0.,  -8., -16., -24.], dtype=torch.float64, grad_fn=<MulBackward0>)